### ISSUE TITLE
UX Flow for Primary Archetypes

### ISSUE THREAD

**Issue by dominicpanarello** [UMEC/healthcare-workforce#4]
This is a story containing the work of building out a high level flows for the primary archetypes. 

For the Administrators, Educators, Clinician, and Legislator Archetypes, they need to be focused on manipulating  and entering data, and receiving data as a result in order to make a decision.

For the Health Researchers, they will need an interface to manipulate the model and curate the data that the other archetypes will use.

**Comment by Randy-Gregory-II** [comment]
Story 1:
Someone in charge of producing a behavioral health program at the university needs to understand the current counts of psychologists in the counties of Utah, as they think there might be an opportunity to fulfill the need for psychologists through a new program at the university, based on understanding that the country is in need of more mental health specialists.  

First, they open up the tool and they make a query for all psychologists and behavioral therapists across the 29 counties. If they wanted to, they could also search per county or any selection of counties.  The tool brings back a count of the amount of behavioral health specialists in the counties.  The user then needs to figure out what the current need is, which is determined by the reporting rates from the different counties. 

There is a catch though, in that the user understands that 50% of mental health challenges are not reported, but the tool factors that in.    Now the user has the number of current specialists in the counties, alongside an estimate of potential need.

The end result is a report that shows the difference between the Roles Active and the Population needs. The user could then make an educated guess on numbers needed based on this report.

**Comment by Randy-Gregory-II** [comment]
https://ibm.box.com/s/mj0ryxxkqr30mq0a0s8fpxw6suxpb7wn - Academic flow
https://ibm.box.com/s/9kxkil2irx4v4sz3hvn37qnvxubunj4o - Hiring flow

**Comment by Randy-Gregory-II** [comment]
We've produced 3 flows so far that align to our user needs. They need some more refinement and some questions answered by our stakeholders.
