### ISSUE TITLE
Review questions for Joel on first IBM check-in

### ISSUE THREAD

**Issue by dominicpanarello** [UMEC/healthcare-workforce#54]

**Comment by lexicas** [comment]
Topics of Discussion:
1) Do have a shared agreement and vision with the Partner?
2) Can you articulate the value that the vision will create? In the short, medium and long term
3) Do we have full productive utilization of the team’s time?
4) What needs to be prepared at IBM and the partner for this to start delivering value?
5) Is the partner going to be able to own, grow and operate this service when you have left?
